[package]
name = "cli_marco"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cli = { version="2.0.2", path = "../../uymas/cli", package = "uymas_cli", features = ["cli-derive"]}
